![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)

------------
# What is Numpy?
NumPy is a general-purpose array-processing package which provides a high-performance, homogenous, multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:
- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
    
Using numpy we ca create 1 Dimensional array, 2 Dimensional array, and 3 Dimensional array
    
Advantages os NumPy over List.
- NumPy is very fast.
- Numpy uses fixed type.
- NumPy's arrays are more compact than Python lists.
- Uses less system memory.
- No type checking when iterating through objects.
- NumPy uses continus memory.
    * Uses SIMD Vector Processing.
    * Effective Cache Utilization

Applications of NumPy.
- Mathematics(MatLAB Replacement)
- Plotting(Matplotlib)
- Backend(Pandas, Connect 4, Digital Photography)
- Machine Learning



[YouTube](https://www.youtube.com/watch?v=GB9ByFAIAH4)
[YouTube](https://www.youtube.com/watch?v=cymDVY_pkYo)

In [1]:
!pip install numpy

### The Basics

In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


**Get the Dimensions**

In [14]:
a.ndim

1

In [13]:
b.ndim

2

In [15]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

**Get the type**

In [17]:
a.dtype

dtype('int64')

In [18]:
b.dtype

dtype('float64')

In [19]:
c = np.array([1,2,3], dtype='int16')
print(a)
c.dtype

[1 2 3]


dtype('int16')

**Get size** (how much memory using for each element)

In [20]:
a.itemsize

8

In [22]:
b.itemsize

8

In [23]:
c.itemsize

2

**Get total size** (how much memory used by the array)

In [28]:
# Get total size 
a.size * a.itemsize

# or use .nbytes

24

In [24]:
a.nbytes

24

In [25]:
b.nbytes

48

In [26]:
c.nbytes

6

### Accessing/Changing Specific elements, rows, columns, etc

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


**Get a specific element   array[row, column]**

In [31]:
a[1, 0]

8

In [32]:
a[1, 5]

13

In [34]:
#using -ive notation
a[1, -2]

13

**Get a specific row**

In [35]:
# get the 1st row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

**Get a specific column**

In [38]:
#get the 3rd column
a[:, 2]

array([ 3, 10])

**Getting specific elements [startindex:endindex:stepsize]**

In [42]:
# 

print(a)
a[0, 1:6:2]


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

**Changing an element**

In [47]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print()

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**Change all elements in a column**

In [48]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print()

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [50]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print()

a[:,2] = [44, 88]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[ 1  2 44  4  5  6  7]
 [ 8  9 88 11 12 13 14]]


**Change elements in a row**

In [49]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print()

a[1,:] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[1 2 3 4 5 6 7]
 [5 5 5 5 5 5 5]]


In [51]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print()

a[1,:] = [11,22,33,44,55,66,77]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[ 1  2  3  4  5  6  7]
 [11 22 33 44 55 66 77]]


**Working with 3D array**

In [7]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# get a specific element (work outside in)
# for example, get the value 4

x[0, 1, 1]

4

In [57]:
#2nd row in each block**
x[:, 1, :]

array([[3, 4],
       [7, 8]])

**Replacing elements in 3D array** (should be same dimension)

In [64]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
x[:, 1, :] = [[99,88],[44,33]]
print(x)

[[[ 1  2]
  [99 88]]

 [[ 5  6]
  [44 33]]]


### Initilizing Different Types of Arrays

**All zero metrix**

**1D**

In [67]:
np.zeros(4)

array([0., 0., 0., 0.])

**2D**

In [68]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**3D**

In [69]:
np.zeros((4,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

**4 Dimensional**

In [70]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

**All One Metrix**

In [72]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [80]:
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

**Any Other number**

In [3]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [5]:
np.full((2,2), 88, dtype='float32')

array([[88., 88.],
       [88., 88.]], dtype=float32)

**Copy the shape of another array and fill with a number**

In [8]:
np.full_like(x, 8)

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

**Random Decimal numbers**

In [10]:
np.random.rand(4,2)

array([[0.92107082, 0.05872838],
       [0.30071411, 0.07337864],
       [0.5142927 , 0.84634545],
       [0.61005126, 0.408122  ]])

In [11]:
np.random.rand(4,2,3)

array([[[0.0498204 , 0.03496364, 0.10296038],
        [0.98976428, 0.19084494, 0.11513763]],

       [[0.61221378, 0.04376979, 0.24498881],
        [0.47475765, 0.27612242, 0.41717595]],

       [[0.43892491, 0.63818084, 0.87391463],
        [0.64390165, 0.72403376, 0.07909496]],

       [[0.88721231, 0.85074042, 0.56270299],
        [0.0543852 , 0.11557994, 0.34588222]]])

**Random Integer numbers**

In [13]:
np.random.randint(7, size=(4,4))

array([[5, 1, 6, 0],
       [2, 1, 2, 4],
       [6, 0, 5, 6],
       [0, 2, 0, 4]])

**Identity Metrix**

In [15]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Making 2D array by repeating the values**

In [18]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Exercise 1** 

[Link](https://youtu.be/GB9ByFAIAH4?t=1975)

In [24]:
# creating a specified output** 

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print()

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying array**

In [31]:
a= np.array([1,2,3])
b = a
print(a)
print()

b[0] = 100

print(a)
print()
print(b)

[1 2 3]

[100   2   3]

[100   2   3]


In [32]:
a= np.array([1,2,3])
b = a.copy()
print(a)
print()

b[0] = 100

print(a)
print()
print(b)

[1 2 3]

[1 2 3]

[100   2   3]


### Mathematics

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
a - 2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
a += 2
a

array([5, 6, 7, 8])

In [41]:
a = np.array([1,2,3,4])
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [42]:
a = np.array([1,2,3,4])
a ** 2

array([ 1,  4,  9, 16])

In [43]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])