# Numpy Arrays

[YouTube](https://www.youtube.com/watch?v=j5EvjSLeRqg)

---
NumPy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called *axes*. The number of axes is *rank*.
- NumPy’s array class is called **ndarray**. It is also known by the alias **array**. 

![](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)

- axis 0 : Represents Rows
- axis 1 : Represents Columns
- axis 2 : 

For example:
```python
[[ 1, 2, 3],
 [ 4, 2, 5]]
```  
This array has:
- rank = 2 (as it is 2-dimensional or it has 2 axes)
- first dimension(axis) length = 2 (two rows), second dimension has length = 3 (3 column).
- overall shape can be expressed as: (2, 3)

In [5]:
import numpy as np

In [7]:
mylist = [[1,2,3],
          [4,5,6]]
a = np.array(mylist)
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(2, 3)

In [10]:
a.dtype

dtype('int64')

In [14]:
mylist = [[1,2,3.0],
          [4,5,6]]
b = np.array(mylist)
print(b)
b.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

In [16]:
mylist = [[1,2,3.0],
          [4,5,6]]
c = np.array(mylist, dtype=complex)
print(c)
c.dtype

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


dtype('complex128')