## Array Creation

[YouTube](https://www.youtube.com/watch?v=Wa0e6R3sZWc)

---

There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the **array** function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [3]:
import numpy as np

In [4]:
mylist = [[1,2,3],
          [4,5,6]]

In [5]:
array = np.array(mylist)

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. **For example:** np.zeros, np.ones, np.full, np.empty, np.random.random, np.random.randint etc.

**numpy.zeros**
- numpy.zeros(shape, dtype=float, order='C')
    - Return a new array of given shape and type, filled with zeros.

In [6]:
arr = np.zeros((4,4))

In [7]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr.dtype

dtype('float64')

In [11]:
arr = np.zeros((4,4), dtype='int')

In [12]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
arr.dtype

dtype('int64')

**numpy.ones**
- numpy.ones(shape, dtype=None, order='C')[source]
    - Return a new array of given shape and type, filled with ones.

In [14]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**numpy.full**
- numpy.full(shape, fill_value, dtype=None, order='C')[source]
    - Return a new array of given shape and type, filled with fill_value.

In [16]:
np.full((4,2), 8)

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

**numpy.empty**
- numpy.empty(shape, dtype=float, order='C')
    - Return a new array of given shape and type, without initializing entries.
    
    - empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [18]:
np.empty((2,2))

array([[6.91024876e-310, 4.64948590e-310],
       [4.64948587e-310, 4.64948588e-310]])

In [19]:
np.empty([2, 2], dtype=int)

array([[139864992004984,  94106642302704],
       [ 94106641754816,  94106641967120]])

**numpy.random.random**
- numpy.random.random(size=None)
    - Return random floats in the half-open interval [0.0, 1.0).

In [21]:
np.random.random((2,2))

array([[0.45862854, 0.07007648],
       [0.83462645, 0.92006588]])

**numpy.random.randint**
- numpy.random.randint(low, high=None, size=None, dtype='l')
    - Return random integers from low (inclusive) to high (exclusive).

In [23]:
np.random.randint(1,10,(3,3))

array([[3, 8, 2],
       [5, 3, 3],
       [9, 2, 2]])

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
   - **arange:** returns evenly spaced values within a given interval. **step** size is specified.
   - **linspace:** returns evenly spaced values within a given interval. **num** no. of elements are returned.

In [25]:
np.array(list(range(10))) #Could not specity step with float values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**numpy.arange**
- numpy.arange([start, ]stop, [step, ]dtype=None)
    - Return evenly spaced values within a given interval.


In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

**numpy.linspace**
- numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
    - Return evenly spaced numbers over a specified interval.
    - Returns num evenly spaced samples, calculated over the interval [start, stop].
    - The endpoint of the interval can optionally be excluded.

In [29]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])