## Array Reshaping
---
We can use **reshape** method to reshape an array. Consider an array with shape (a1, a2, a3, ..., aN). We can reshape and convert it into another array with shape (b1, b2, b3, ....., bM). The only required condition is:   

*a1 x a2 x a3* .... *x aN = b1 x b2 x b3* .... *x bM*

(i.e original size of array remains unchanged.)

In [2]:
import numpy as np

In [8]:
a = np.array([[1,2,3,4,5,6,7,8]])

In [9]:
a.shape

(1, 8)

Example array shapes:
```
(1,8) => (2,4) => (4,2) => (2,2,2) => (8,) => (1,2,2,2)
```

**numpy.reshape**
- numpy.reshape(a, newshape, order='C')[source]
    - Gives a new shape to an array without changing its data.

In [11]:
a.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

![](https://i.imgur.com/pwkcvrD.png)

**Row Major Order Reshape** 
- Default Behavior

In [12]:
a.reshape((2,4), order='C') 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Column Major Order Reshape**

In [13]:
a.reshape((2,4), order='F') 

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

## Array Flattening
---
We can use **flatten** method to get a copy of array collapsed into **one dimension**. It accepts *order* argument. Default value is 'C' (for row-major order). Use 'F' for column major order.

**numpy.ndarray.flatten** [method]
- ndarray.flatten(order='C')
    - Return a copy of the array collapsed into one dimension.

In [14]:
x = np.array([[1,2,3],
              [4,5,6]])

**Row Major Order Flattening**
- Default Behavior

In [15]:
x.flatten()

array([1, 2, 3, 4, 5, 6])

**Column Major Order Flattening**

In [18]:
x.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

**Using reshape to do flattening**
- Note: You need to first know the size of array to use reshape

In [19]:
x.reshape((6,))

array([1, 2, 3, 4, 5, 6])