# Array Indexing
[YouTube](https://www.youtube.com/watch?v=b8IpJT05uBo)

---
Knowing the basics of array indexing is important for analysing and manipulating the array object.
NumPy offers many ways to do array indexing.

- **Positive tuple indexing**

[Documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

In [1]:
import numpy as np

In [2]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6,0, 7,8],
                [3, -7, 4, 2.0]])

In [3]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [5]:
# Called Positive tuple indexing
arr[2,1]

0.0

![](https://i.imgur.com/fzoXLq1.png)

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [6]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [13]:
# To get 1st two rows.

arr[:2]

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ]])

In [11]:
# To get the 1st two rows and 1st three column (2 X 3)

arr[:2,:3]

array([[-1. ,  2. ,  0. ],
       [ 4. , -0.5,  6. ]])

In [12]:
#Get 1st two column

arr[:, :2]

array([[-1. ,  2. ],
       [ 4. , -0.5],
       [ 2.6,  0. ],
       [ 3. , -7. ]])

![](https://i.imgur.com/Tr6SAwv.png)

- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [14]:
arr[0,0]

-1.0

In [15]:
# Indexing Diagonally

arr[[0,1,2,3],[0,1,2,3]]

array([-1. , -0.5,  7. ,  2. ])

- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [16]:
arr > 0

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [19]:
# Create a new array with only the conditions are true

arr[arr > 0]

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])