# Array Sorting
---
There is a simple **np.sort** method for sorting NumPy arrays.


In [1]:
import numpy as np

In [2]:
arr = np.array([[1,4,2],
                [3,4,6],
                [0,-1,5]])

In [3]:
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

**numpy.sort**
- numpy.sort(a, axis=-1, kind=None, order=None)[source]
    - Return a sorted copy of an array.

In [7]:
np.sort(arr)          #Default is axis = -1 Row wise sorting.

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [8]:
np.sort(arr, axis=-1) #row wise sorting.

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [10]:
np.sort(arr, axis=1)  #row wise sorting.

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [9]:
np.sort(arr, axis=0) #column wise sorting.

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [13]:
np.sort(arr, axis=None)  # Sort & create One Dimensional Array

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])