## Array Stacking and Splitting
[YouTube](https://www.youtube.com/watch?v=L5TBwa9sD78)

---
### Stacking

Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.row_stack:** To stack 1-D arrays as rows into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[5, 6],
       [7, 8]])

**numpy.vstack**
- numpy.vstack(tup)
    - Stack arrays in sequence vertically (row wise).

In [6]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**numpy.hstack**
- numpy.hstack(tup)
    - Stack arrays in sequence horizontally (column wise).

In [7]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**numpy.column_stack**
- numpy.column_stack(tup)
    - Stack 1-D arrays as columns into a 2-D array.

In [8]:
c = np.array([0,0])

In [10]:
np.column_stack((a, c))

array([[1, 2, 0],
       [3, 4, 0]])

**numpy.row_stack**
- numpy.row_stack(tup)
    - Stack 1-D arrays as rows into a 2-D array.

In [16]:
np.row_stack((a, c))

array([[1, 2],
       [3, 4],
       [0, 0]])

**numpy.concatenate**
- numpy.concatenate((a1, a2, ...), axis=0, out=None)
    - Join a sequence of arrays along an existing axis.

    - Parameters: a1, a2, … : sequence of array_like
        - The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

        - axis : int, optional
            - The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

        - out : ndarray, optional
            - If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

    - Returns:	res : ndarray
        - The concatenated array.

In [22]:
d = np.array([[11,12],
              [13,14]])

np.concatenate((a, b, d), axis=1)

array([[ 1,  2,  5,  6, 11, 12],
       [ 3,  4,  7,  8, 13, 14]])

### Splitting

For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [23]:
a = np.array([[1, 3, 5, 7, 9,  11],
              [2, 4, 6, 8, 10, 12]])

**numpy.hsplit**
- numpy.hsplit(ary, indices_or_sections)
    - Split an array into multiple sub-arrays horizontally (column-wise).

In [24]:
np.hsplit(a, 2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

**numpy.vsplit**
- numpy.vsplit(ary, indices_or_sections)
    - Split an array into multiple sub-arrays vertically (row-wise).

In [25]:
np.vsplit(a, 2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

**numpy.array_split**
- numpy.array_split(ary, indices_or_sections, axis=0)
    - Split an array into multiple sub-arrays.

In [32]:
np.array_split(a, 2, axis=0)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [30]:
np.array_split(a, 3, axis=1)

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]