# Saving and loading numpy arrays
[YouTube](https://www.youtube.com/watch?v=JRXhCmmLbeY)

---

The ``.npy`` format is the standard binary file format in NumPy for
persisting a **single** arbitrary NumPy array on disk. The format stores all
of the shape and dtype information necessary to reconstruct the array
correctly even on another machine with a different architecture.
The format is designed to be as simple as possible while achieving
its limited goals.

The ``.npz`` format is the standard format for persisting **multiple** NumPy
arrays on disk. A ``.npz`` file is a zip file containing multiple ``.npy``
files, one for each array.

- **np.save(filename, array)** : saves a single array in ``npy`` format.

- **np.savez(filename, array_1[, array_2])** : saves multiple numpy arrays in ``npz`` format.

- **np.load(filename)** : load a ``npy`` or ``npz`` format file.

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[6,5,4],
              [3,2,1]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b

array([[6, 5, 4],
       [3, 2, 1]])

In [5]:
np.save("a.npy", a)

In [6]:
!ls -al *.npy

-rw-r--r-- 1 root root 176 Dec 22 02:31 a.npy


In [7]:
!cat a.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 3), }                                                          


In [9]:
p = np.load('a.npy')

In [10]:
p

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.savez('ab.npz', x=a, y=b)

In [12]:
!ls -al *.n*

-rw-r--r-- 1 root root 176 Dec 22 02:31 a.npy
-rw-r--r-- 1 root root 586 Dec 22 02:35 ab.npz


In [13]:
arr = np.load('ab.npz')

In [14]:
arr

In [15]:
arr['x']

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr['y']

array([[6, 5, 4],
       [3, 2, 1]])